---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  releaseName: influxdb
  chart:
    git: https://github.com/influxdata/helm-charts
    path: tree/master/charts
    ref: master
    version: 4.8.10
  values:
    image:
      repository: "influxdb"
      tag: "1.8.3"
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      size: 50Gi
      storageClass: nfs-csi
    resources:
      requests:
        memory: 2000Mi
        cpu: 100m
      limits:
        memory: 4000Mi
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
    config:
      opentsdb:
        enabled: true
      graphite:
        enabled: true
        database: graphitedb
        retention-policy: ""
        bind-address: ":2003"
        protocol: tcp
        consistency-lvel: one
        templates:
        - "*.app env.service.resource.measurement"
        - "servers.* .host.resource.measurement.field*"
    podAnnotations:
      backup.velero.io/backup-volumes: influxdb-data
    tolerations:
    - key: "arm"
      operator: "Exists"